var config = {
    texts: [
        "For Teacher Li",
        "今天是个特别的日子",
        "李老师硕士毕业的第一个生日",
        "相识六年,见证了你的太多成长",
        "可心李俨然成为了真正的李老师",
        "再回首,上一次见面已定格在2014",
        "期待未来与你相聚",
        "Happy Birthday!",
        "祝冰雪聪明的李大仙",
        "生日快乐!",
        "工作顺利!",
        "事业有成!",
        "永远单身!!!",
        "哎呀,我突然想起来",
        "李老师说我过生日的时候",
        "要送我一个Apple耳机",
        "如今我研究生都毕业了",
        "也未曾看到过耳机的影子",
        "是不是觉得很过意不去?",
        "没事,爸爸原谅你了",
        "哈哈哈哈!",
        "End!",
    ],
    imgs: {
        "For Teacher Li": "./imgs/kexin1.jpg",
        "今天是个特别的日子": "./imgs/special.jpeg",
        "李老师硕士毕业的第一个生日": "./imgs/master.jpeg",
        "相识六年,见证了你的太多成长": "./imgs/growth.jpeg",
        "可心李俨然成为了真正的李老师": "./imgs/chemistry.jpeg",
        "再回首,上一次见面已定格在2014": "./imgs/2014.jpeg",
        "期待未来与你相聚": "./imgs/connect.jpeg",
        "Happy Birthday!": "./imgs/cake1.jpg",
        "祝冰雪聪明的李大仙": "./imgs/kexin2.jpg",
        "生日快乐!": "./imgs/cake2.jpg",
        "工作顺利!": "./imgs/work.jpeg",
        "事业有成!": "./imgs/money.jpeg",
        "永远单身!!!": "./imgs/single.png",
        "哎呀,我突然想起来": "./imgs/remind.jpeg",
        "李老师说我过生日的时候": "./imgs/cookie.jpeg",
        "要送我一个Apple耳机": "./imgs/earphone.jpeg",
        "如今我研究生都毕业了": "./imgs/ceremony.jpeg",
        "也未曾看到过耳机的影子": "./imgs/forget.jpeg",
        "是不是觉得很过意不去?": "./imgs/guilty.jpeg",
        "没事,爸爸原谅你了": "./imgs/forgive.png",
        "哈哈哈哈!": "./imgs/happy.jpeg",
    },
    desc: {
        turn_on: "Ready?",
        play: "Music",
        bannar_coming: "贺卡",
        balloons_flying: "好像少点东西",
        cake_fadein: "蛋糕？",
        light_candle: "蜡烛？",
        wish_message: "生日快乐",
        story: "A MESSAGE FOR YOU",
    }
};
